//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoldingAtomata {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoldingAtomata.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PyON1topology
        ///{
        ///&quot;atoms&quot;:[
        ///[&quot;N&quot;,0.1849,1.625,14.01,7],
        ///[&quot;H1&quot;,0.1898,1.15,1.008,1],
        ///[&quot;H2&quot;,0.1898,1.15,1.008,1],
        ///[&quot;H3&quot;,0.1898,1.15,1.008,1],
        ///[&quot;CA&quot;,0.0567,1.9,12.01,6],
        ///[&quot;HA&quot;,0.0782,1.25,1.008,1],
        ///[&quot;CB&quot;,0.2596,1.9,12.01,6],
        ///[&quot;HB1&quot;,0.0273,1.25,1.008,1],
        ///[&quot;HB2&quot;,0.0273,1.25,1.008,1],
        ///[&quot;OG&quot;,-0.6714,1.535,16,8],
        ///[&quot;HG&quot;,0.4239,1.05,1.008,1],
        ///[&quot;C&quot;,0.6163,1.875,12.01,6],
        ///[&quot;O&quot;,-0.5722,1.48,16,8],
        ///[&quot;N&quot;,-0.2548,1.7063,14.01,7],
        ///[&quot;CD&quot;,0.0192,1.9,12.01,6],
        ///[&quot;HD1&quot;,0.0391,1.25,1.008,1],
        ///[&quot;HD2&quot;,0.0391,1.25,1.008,1],
        ///[&quot;CG&quot;,0.018 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string demoProtein {
            get {
                return ResourceManager.GetString("demoProtein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gradient {
            get {
                object obj = ResourceManager.GetObject("gradient", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
